/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Ventas;


import FrmTicket.imprimir;
import Modelo.LogicaProductos;

import Modelo.VO.ProductosVO;
import javax.swing.JOptionPane;
/**
 *
 * @author sistema
 */
public class FrmVentas extends javax.swing.JFrame {

    public static String getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();
       txtNombre.setEditable(false);
       txtClave.setEditable(false);
       txtDescripcion.setEditable(false);
       txtNO4.setEditable(false);
       txtNOVentas.setEditable(false);
       this.setSize(845, 570);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBarras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNO4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNOVentas = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtBarras);
        txtBarras.setBounds(20, 50, 255, 27);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Ventas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(345, 0, 119, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Codigo de barras:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 154, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 250, 80, 19);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(10, 280, 422, 27);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setText("Clave del producto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 152, 19);
        getContentPane().add(txtClave);
        txtClave.setBounds(20, 200, 255, 25);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Descripcion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 320, 91, 19);

        txtDescripcion.setFont(new java.awt.Font("Dialog", 3, 8)); // NOI18N
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(10, 350, 420, 25);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText("Precio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 430, 61, 14);
        getContentPane().add(txtNO4);
        txtNO4.setBounds(90, 430, 135, 25);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText("Total:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 470, 54, 19);

        txtNOVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOVentasActionPerformed(evt);
            }
        });
        getContentPane().add(txtNOVentas);
        txtNOVentas.setBounds(530, 470, 160, 25);

        btnCalcular.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(10, 460, 118, 29);

        btnImprimir.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnImprimir.setText("Imprimir Ticket");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(280, 460, 165, 29);

        btnMenu.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnMenu.setText("Salir");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(770, 460, 65, 29);

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel9.setText("NO. Piezas:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 430, 75, 19);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(360, 430, 100, 25);

        jButton1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 120, 100, 25);

        jToggleButton1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jToggleButton1.setText("Seleccionar");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(140, 120, 102, 26);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo de barras", "Nombre", "Precio", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(433, 30, 430, 400);

        jToggleButton2.setText("Buscar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(30, 120, 69, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventas/ventas.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 0, 810, 400);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventas/ventas.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 70, 420);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventas/ventas.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 370, 440, 430);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ventas/ventas.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 361, 430, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        //MenuPrincipal menu= new MenuPrincipal();menu.setVisible(true);this.setVisible(false);
         int ce;
        ce = JOptionPane.showConfirmDialog(this, "¿Esta apunto de abandonar el sistema desea continuar?","ADVERTENCIA" ,JOptionPane.YES_NO_OPTION);
       if(ce==JOptionPane.YES_OPTION){
           System.exit(1);
       }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
         int ce;
        ce = JOptionPane.showConfirmDialog(this, "¿Esto es para confirmar su compra desea continuar ?","ADVERTENCIA" ,JOptionPane.YES_NO_OPTION);
       if(ce==JOptionPane.YES_OPTION){
           imprimir ventas= new imprimir();ventas.setVisible(true);this.setVisible(false);
       }
        
         
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtNOVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOVentasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtBarras.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField txtBarras;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNO4;
    public javax.swing.JTextField txtNOVentas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
