/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Inicio;


import Modelo.LogicaLogin;
import Modelo.VO.UsuariosVO;
import Vista.MenuPrincipal.MenuPrincipal;
import controlador.Coordinator;



import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sistema
 */
public class Login extends javax.swing.JFrame {
    SplashScreen inicio;
    
    
    private Coordinator ClassCoordinador; //objeto miCoordinador que permite la relacion entre esta clase y la clase coordinador
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setSize(410, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/logoFerre.png")).getImage());
        this.setTitle("ACCESO - SISTEMA FERRETERIA");
    }
    
    public Login(SplashScreen inicio)
    {
        this.inicio = inicio;
        setProgress(0, "Cargando Componentes del Sistema");
        initComponents();
        this.setSize(410, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/logo.png")).getImage());
        this.setTitle("ACCESO - SISTEMA ENRAMADA FERRETERIA");
        setProgress(20, "Conectandose a la Base de Datos...");
        setProgress(40, "Cargando Modulos..");
        setProgress(60, "Carga de Modulos Terminada");
        setProgress(80, "Cargando Interfaces..");
        setProgress(90, "Interfaces Cargadas");
        setProgress(100, "Bienvenido al Sistema");
        this.setLocationRelativeTo(null);
    }
    void setProgress(int percent, String information) 
    {
        inicio.getJLabel().setText(information);
        inicio.getJProgressBar().setValue(percent);

        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo ejecutar la presentación");
        }
    }
    
   
    
    public void setCoordinador(Coordinator ClassCoordinador) {
		this.ClassCoordinador=ClassCoordinador;
	}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        btnentrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 160, 80, 17);

        usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usuarioKeyReleased(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(60, 200, 240, 21);

        contraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(contraseña);
        contraseña.setBounds(60, 270, 240, 21);

        btnentrar.setText("Aceptar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar);
        btnentrar.setBounds(220, 310, 80, 40);

        btnsalir.setText("Cancelar");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(60, 310, 100, 40);

        labelMetric3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric3.setText("¡¡¡ bienvenido a Ferre Rony !!!");
        labelMetric3.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        getContentPane().add(labelMetric3);
        labelMetric3.setBounds(20, 100, 360, 30);
        labelMetric3.getAccessibleContext().setAccessibleName("¡¡¡ bienvenido a Ferre Roni !!!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/Login.png"))); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 490, 145);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 240, 80, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
    System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        String us = usuario.getText();
        String pas = contraseña.getText();
        if (us.equals("") || pas.equals("")) {
            JOptionPane.showMessageDialog(this, "Los campos son obligatorios", "Acceso", 0,
                    new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/info.png")));
        } else {
         
            
            LogicaLogin ob =new LogicaLogin();
                 
            
            UsuariosVO Validate= ob.InicioLogin(us, pas);
            
            try {
                 if(Validate.getActivo())
                 {
                         dispose();
                         
                        MenuPrincipal mp = new MenuPrincipal(Validate.getIdTipoUsuarioFK(),Validate.getNombre());
                        JOptionPane.showMessageDialog(this, "BIENVENIDO: " + Validate.getNombre()+" "+Validate.getApellidoP(), "Administrador", 0,
                                new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/Accept-Male-User.png")));
                       // mp.setNombre(Validate.getNombre());
                       // mp.setIdTipoUsuarioFk(Validate.getIdTipoUsuarioFK());//mp.userConect.setText(dato);
                       //mp.IdTipoUsuarioFk=Validate.getIdTipoUsuarioFK();
                        mp.setVisible(true);
                 }
                 else
                 {
                   JOptionPane.showMessageDialog(this, "El usuario se encuentra dado de baja contacte al administrador", "Acceso", 0,
                    new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/info.png")));
                 }
                 
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta", "Acceso", 0,
                    new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/info.png")));
            }
            
                
                    

            
            
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnentrarActionPerformed

    
    
    private void muestraPersona(UsuariosVO Validate) {
		String nombrew= Validate.getNombre();
	}
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     if (JOptionPane.showConfirmDialog(this, "Esta a punto de salir\nde la aplicación.\n¿Desea continuar?", "Cerrar", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Recursos/Imagenes/Inicio/adver32x32.png"))) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }else{
            this.setDefaultCloseOperation(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyReleased
        usuario.setText(usuario.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
